### ISSUE TITLE
Enhance the sidekiq initializer file

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto_commons#127]
- [ ] We ought to enable sidekiq inline for `test` envs by default right? I believe we will be requiring inlining more often than fake testing. If we don't add this, then we will have to add `Sidekiq::Testing.inline!` in all tests `setup` method and repeat it. Thus, one more condition required here: `if Rails.env.test? || Rails.env.heroku?`https://github.com/bigbinary/neeto_commons/blob/a811ed3d43559df015719b7b21d32f3c2c2e58b5/lib/neeto_commons/initializers/sidekiq.rb#L10-L13
- [ ]  We should wrap loading of cron schedules within `unless Rails.env.test?`, because in test env I don't think there is any use case for loading cron jobs in most cases. Even if it's needed in the rare case, maybe allow a ENV variable to override this. Here loading cron jobs in the `test` env is unnecessary:
https://github.com/bigbinary/neeto_commons/blob/a811ed3d43559df015719b7b21d32f3c2c2e58b5/lib/neeto_commons/initializers/sidekiq.rb#L32-L36

@unnitallman _a Please take a look into this and assign to the right person. Thanks.

cc: @sandip-mane Lemme know if in neetoDesk or somewhere if we need to load cron jobs for testing etc. In that case we should add an env variable to override.

**Comment by sandip-mane** [comment]
In neetoDesk or any other app I worked on, we are not testing the trigger part of the jobs. We enqueue the job and make sure it does what it is supposed to do.

So I guess we are good even if we do not load cron jobs in test.

**Comment by prasanthchaduvula** [comment]
@prasanthchaduvula _a
