### ISSUE TITLE
Replace byebug and pry with a pry-byebug.

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/neeto_commons#134]
Replace `byebug` and `pry` with a single `pry-byebug`.
It supports debugging via both the syntaxes (binding.pry or byebug) and has capabilities of both.

P.S: The author of pry-byebug and byebug is the same.

Replace 

https://github.com/bigbinary/neeto_commons/blob/ad572ef31f20d1d90ceafff1decc93a78d12c93b/lib/neeto_commons/gemfiles/Gemfile.common.rb#L157-L161

with 

https://github.com/bigbinary/wheel/blob/b5aa0569a782f6b3c48acd52e6c392268a115276/Gemfile#L57-L59

**Comment by unnitallman** [comment]
@prasanthchaduvula _a
