### ISSUE TITLE
Increase rack::attack throttling limits

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/neeto_commons#154]
The current limit is
```
  # Allows 240 requests/IP in ~8 minutes
  #        480 requests/IP in ~1 hour
  #        960 requests/IP in ~8 hours (~2,880 requests/day)
```
Reference: (https://www.bigbinary.com/blog/how-to-mitigate-ddos-using-rack-attack)
https://github.com/bigbinary/neeto_commons/blob/532f5f0b3cddc57ff8ef1b66a29308e86af6cc5d/lib/neeto_commons/initializers/rack_attack.rb#L26-L32

This is too little for a production application. We are encountering problems in neetoChat.
[Verify Rack Attack configuration on production / Possibility of too many requests per chat show #2732](https://github.com/bigbinary/neeto-chat-web/issues/2732)
The issue will be more frequent when there are multiple support agents working from an office with a single router (same public IP).
The number of requests will definitely go beyond 960 per 8 hours.

@unnitallman _a

**Comment by unnitallman** [comment]
Not needed. Instead we have turned off Rack::Attack by default on all Neeto apps. We can turn it on if/when needed via an environment variable.
