### ISSUE TITLE
Move commonly used gems to neeto_commons

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto_commons#20]
```
gem "rails", "6.1.4.1"

# To read variables from .env.* files to ENV
gem "dotenv-rails"

# Postegresql database adapter for ActiveRecord
gem "pg"

# JSON view builder
gem "jbuilder"

# Error tracking
gem "honeybadger"

# Application server
gem "puma"

# Faster env load times
gem "bootsnap"

# Generate fake data 
gem "faker"

# To inject React components in views and pass props from server
gem "react-rails"

# Pagination
gem "kaminari"

# Application Performance Monitor
gem "newrelic_rpm"

# I18n Internationalization
gem "rails-i18n"

# Redis
gem "redis"

# S3 adapter for ActiveStorage
gem "aws-sdk-s3", require: false

# Authorization
gem "pundit"
```

**Comment by prasanthchaduvula** [comment]
gem "rails", "6.1.4.1"

# To read variables from .env.* files to ENV
gem "dotenv-rails"

# Postegresql database adapter for ActiveRecord
gem "pg"

# JSON view builder
gem "jbuilder"

# Error tracking
gem "honeybadger"

# Application server
gem "puma"

# Faster env load times
gem "bootsnap"

# Generate fake data 
gem "faker"

# To inject React components in views and pass props from server
gem "react-rails"

# Pagination
gem "kaminari"

# Application Performance Monitor
gem "newrelic_rpm"

# I18n Internationalization
gem "rails-i18n"

# Redis
gem "redis"

# S3 adapter for ActiveStorage
gem "aws-sdk-s3", require: false

# Authorization
gem "pundit"

**Comment by prasanthchaduvula** [comment]
```
gem "rails", "6.1.4.1"

# Related to AssetPipeline
gem "uglifier"

```

**Comment by prasanthchaduvula** [comment]
Create `Gemfile.common.rb` file which will have all the commonly used gems. We will add the same gemfile in all neeto apps and load` eval_gemfile "Gemfile.common.rb"` in the apps gemfile. We will create a verfier in compliance for standardization purpose.
