### ISSUE TITLE
Set production log_level to "error"

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto_commons#209]
We are running production with log_level `debug`. This is not ideal. 

@prasanthchaduvula _a

**Comment by prasanthchaduvula** [comment]
@unnitallman Do we have to change both app.json and newrelic.yml

in app.json
we have ```
"LOG_LEVEL": {
      "value": "DEBUG"
    },
```

in newrelic.yml we have
`log_level: info`

**Comment by unnitallman** [comment]
```
config.log_level = :error
```
