### ISSUE TITLE
Make a list of all gems that are added in development group of all Neeto apps

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto_commons#21]
Also prepare a similar list for `test` group and one for gems that are listed in `[:test, :development]` group as well.

@prasanthchaduvula _a

Attach the lists to this issue.

**Comment by prasanthchaduvula** [comment]
**development group**
- gem "erb_lint", require: false, git: "https://github.com/Shopify/erb-lint.git", branch: "main"
- gem "spring"
- gem "web-console"
- gem "listen"
- gem "rubocop", require: false
- gem "rubocop-minitest", require: false
- gem "rubocop-rails", require: false

**Comment by prasanthchaduvula** [comment]
Handled in #20
