### ISSUE TITLE
What should we set as the APP_URL?

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto_commons#65]
https://github.com/bigbinary/neeto_commons/blob/76d539507db81f6540c3dbd4a1af87004f9fe340/lib/neeto_commons/initializers/email_setup.rb#L19-L23

The `AUTH_APP_URL` is `app.neetoauth.com`.

So if I am setting `APP_URL` for say `neetoEngage`, then should `APP_URL` be `app.neetoengage.com`?

The point of raising this issue is to ensure that we document this here in this repo. The error message should point out example values that this env variable can have.

In Heroku production, in order for the build to succeed, we need to set this env variable.

Not sure who is the tech lead here. Thus assigning this to Ghouse.

@ghousemohamed _a

cc: @prasanthchaduvula @unnitallman

**Comment by ghousemohamed** [comment]
@yedhink Yes, the `APP_URL` env should be of the format **app.neeto`appname`.com**

**Comment by yedhink** [comment]
@yedhink _a

Got it. I will make a PR for this by updating the error message.

**Comment by yedhink** [comment]
@prasanthchaduvula _a

Can you please take this up? Thanks.
