### ISSUE TITLE
Redis Cache configuration

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto_commons#9]
https://github.com/bigbinary/neeto-replay-web/blob/master/config/initializers/redis_cache_store.rb#L1

**Comment by prasanthchaduvula** [comment]
`NeetoCommons::Initializers.redis(config)`

**Comment by unnitallman** [comment]
@prasanthchaduvula Please go through this one also. https://github.com/bigbinary/neeto-form-web/issues/1913
